FROM ubuntu:latest
ENV DEBIAN_FRONTEND noninteractive
MAINTAINER Ram "ram_krishna.shrestha@tsl.ac.uk"

RUN apt-get update && apt-get install -y build-essential wget curl python3-pip python3-dev samtools bowtie2 trimmomatic bwa \
	&& cd /usr/local/bin \
	&& ln -s /usr/bin/python3 python \
	&& pip3 install --upgrade pip


RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh \
	&&     /bin/bash miniconda.sh -b -p /opt/conda \
	&&     rm miniconda.sh \
	&&     /opt/conda/bin/conda clean -tipsy \
	&&     ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh \
	&&     echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc \
	&&     echo "conda activate base" >> ~/.bashrc \
	&&     find /opt/conda/ -follow -type f -name '*.a' -delete 	\
	&&     find /opt/conda/ -follow -type f -name '*.js.map' -delete \	
	&&     /opt/conda/bin/conda clean -afy