FROM ubuntu
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y bowtie2 samtools

ADD ./bowtie2alignment.sh /usr/local/bin/bowtie2alignment

RUN chmod +x /usr/local/bin/bowtie2alignment

CMD ["bowtie2alignment"] 
